apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx-demo
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-nginx
  template:
    metadata:
      labels:
        app: my-nginx
    spec:
      imagePullSecrets:
      - name: acr-secret
      containers:
      - name: nginx-container
        image: crpi-21npa443x69e7rrn.cn-chengdu.personal.cr.aliyuncs.com/greys-wordpress/my-nginx-demo:v1.0
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-nginx-svc
  namespace: default
spec:
  selector:
    app: my-nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
